import { jsPDF } from "jspdf";
import { Transaction, Listing, UserProfile } from "@/types";
import { format } from "date-fns";

export function generateTradeCertificate(transaction: Transaction, listing: Listing, seller: UserProfile, buyer: UserProfile) {
  const doc = new jsPDF();
  
  // Header
  doc.setFillColor(34, 197, 94); // HiX Green
  doc.rect(0, 0, 210, 40, 'F');
  
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(24);
  doc.text("HiX Trade Certificate", 105, 25, { align: "center" });
  
  // Certificate Info
  doc.setTextColor(0, 0, 0);
  doc.setFontSize(12);
  doc.text(`Certificate No: ${transaction.id}`, 20, 50);
  const createdAt = transaction.createdAt?.toDate ? transaction.createdAt.toDate() : new Date(transaction.createdAt);
  doc.text(`Date: ${format(createdAt, 'PPP')}`, 20, 60);
  
  // Transaction Details
  doc.setFontSize(16);
  doc.text("Transaction Details", 20, 80);
  doc.line(20, 82, 190, 82);
  
  doc.setFontSize(12);
  doc.text(`Asset: ${listing?.title || 'Unknown Asset'}`, 20, 95);
  doc.text(`Quantity: ${transaction.quantity} units`, 20, 105);
  doc.text(`Total Amount: £${transaction.amount?.toLocaleString() || '0'}`, 20, 115);
  
  // Sustainability Impact
  doc.setFillColor(240, 253, 244);
  doc.rect(20, 125, 170, 30, 'F');
  doc.setTextColor(21, 128, 61);
  doc.setFontSize(14);
  doc.text("Sustainability Impact", 105, 135, { align: "center" });
  doc.setFontSize(18);
  doc.text(`${transaction.co2Saved} kg CO2 Saved`, 105, 148, { align: "center" });
  
  // Parties
  doc.setTextColor(0, 0, 0);
  doc.setFontSize(16);
  doc.text("Parties Involved", 20, 170);
  doc.line(20, 172, 190, 172);
  
  doc.setFontSize(12);
  doc.text("Seller:", 20, 185);
  doc.text(seller.companyName, 50, 185);
  doc.text(`VAT: ${seller.vatNumber}`, 50, 192);
  
  doc.text("Buyer:", 20, 210);
  doc.text(buyer.companyName, 50, 210);
  doc.text(`VAT: ${buyer.vatNumber}`, 50, 217);
  
  // Footer
  doc.setFontSize(10);
  doc.setTextColor(150, 150, 150);
  doc.text("This certificate is automatically generated by Hartlepool Industrial Exchange (HiX).", 105, 270, { align: "center" });
  doc.text("HiX LTD | Hartlepool, UK | www.hix-exchange.com", 105, 277, { align: "center" });
  
  doc.save(`HiX-Certificate-${transaction.id}.pdf`);
}

export async function generateSustainabilityReport(profile: UserProfile, transactions: Transaction[], logoUrl?: string) {
  const doc = new jsPDF();
  const totalCo2 = transactions.reduce((acc, curr) => acc + (curr.co2Saved || 0), 0);
  const totalVolume = transactions.reduce((acc, curr) => acc + (curr.amount || 0), 0);
  
  // Header with dark aesthetic
  doc.setFillColor(15, 23, 42); // slate-900
  doc.rect(0, 0, 210, 60, 'F');
  
  // Attempt to add logo if available
  if (logoUrl) {
    try {
      const img = new Image();
      img.crossOrigin = "anonymous";
      img.src = logoUrl;
      await new Promise((resolve, reject) => {
        img.onload = resolve;
        img.onerror = reject;
      });
      
      // Draw circular frame
      doc.setDrawColor(34, 197, 94); // HiX Green
      doc.setLineWidth(1);
      doc.circle(25, 30, 15, 'D'); // Circular border
      
      // Add image inside (centered in the circle)
      doc.addImage(img, 'PNG', 13, 18, 24, 24);
    } catch (e) {
      console.error("Could not add logo to sustainability report", e);
    }
  }

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(28);
  doc.text("HiX Sustainability Audit", 115, 30, { align: "center" });
  doc.setFontSize(12);
  doc.text(`Environmental Impact Report for ${profile.companyName}`, 115, 45, { align: "center" });
  
  // High Level Stats Card
  doc.setFillColor(34, 197, 94); // emerald-500
  doc.roundedRect(20, 70, 170, 40, 5, 5, 'F');
  
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(12);
  doc.text("TOTAL CARBON SEQUESTRATION EQUIVALENT", 105, 82, { align: "center" });
  doc.setFontSize(32);
  doc.text(`${totalCo2.toLocaleString()} KG CO2`, 105, 100, { align: "center" });

  // Detail Table
  doc.setTextColor(0, 0, 0);
  doc.setFontSize(16);
  doc.text("Transaction Register", 20, 130);
  doc.line(20, 132, 190, 132);

  doc.setFontSize(10);
  doc.text("ID", 20, 142);
  doc.text("DATE", 50, 142);
  doc.text("ASSET TYPE", 80, 142);
  doc.text("AMOUNT", 130, 142);
  doc.text("CO2 SAVED", 160, 142);
  doc.line(20, 144, 190, 144);

  let y = 152;
  transactions.slice(0, 15).forEach((t, i) => {
    const date = t.createdAt?.toDate ? t.createdAt.toDate() : new Date(t.createdAt);
    doc.text(t.id.slice(0, 8), 20, y);
    doc.text(format(date, 'dd/MM/yy'), 50, y);
    doc.text(t.sellerId === profile.uid ? "Sale" : "Purchase", 80, y);
    doc.text(`£${t.amount.toLocaleString()}`, 130, y);
    doc.text(`${t.co2Saved}kg`, 160, y);
    y += 8;
  });

  // Methodology
  doc.setFillColor(248, 250, 252); // slate-50
  doc.rect(20, 240, 170, 30, 'F');
  doc.setTextColor(100, 116, 139);
  doc.setFontSize(8);
  doc.text("METHODOLOGY:", 25, 248);
  doc.text("This report uses standard industrial carbon coefficients (ISO 14064) based on asset weight and material composition.", 25, 254);
  doc.text("Lifecycle extension is valued against new-unit manufacturing energy baselines. Verified by HiX-AI Node.", 25, 260);

  // Footer
  doc.setFontSize(10);
  doc.text("Verification Date:", 20, 285);
  doc.text(format(new Date(), 'PPP'), 55, 285);
  doc.text("Signature: ______________________", 130, 285);

  doc.save(`HiX-ESG-Report-${profile.companyName.replace(/\s+/g, '-')}.pdf`);
}
