import { jsPDF } from "jspdf";
import { Transaction, Listing, UserProfile } from "@/types";
import { format } from "date-fns";

export function generateTradeCertificate(transaction: Transaction, listing: Listing, seller: UserProfile, buyer: UserProfile) {
  const doc = new jsPDF();
  
  // Header
  doc.setFillColor(34, 197, 94); // HiX Green
  doc.rect(0, 0, 210, 40, 'F');
  
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(24);
  doc.text("HiX Trade Certificate", 105, 25, { align: "center" });
  
  // Certificate Info
  doc.setTextColor(0, 0, 0);
  doc.setFontSize(12);
  doc.text(`Certificate No: ${transaction.id}`, 20, 50);
  doc.text(`Date: ${format(transaction.createdAt, 'PPP')}`, 20, 60);
  
  // Transaction Details
  doc.setFontSize(16);
  doc.text("Transaction Details", 20, 80);
  doc.line(20, 82, 190, 82);
  
  doc.setFontSize(12);
  doc.text(`Asset: ${listing.title}`, 20, 95);
  doc.text(`Quantity: ${transaction.quantity} units`, 20, 105);
  doc.text(`Total Amount: £${transaction.amount.toLocaleString()}`, 20, 115);
  
  // Sustainability Impact
  doc.setFillColor(240, 253, 244);
  doc.rect(20, 125, 170, 30, 'F');
  doc.setTextColor(21, 128, 61);
  doc.setFontSize(14);
  doc.text("Sustainability Impact", 105, 135, { align: "center" });
  doc.setFontSize(18);
  doc.text(`${transaction.co2Saved} kg CO2 Saved`, 105, 148, { align: "center" });
  
  // Parties
  doc.setTextColor(0, 0, 0);
  doc.setFontSize(16);
  doc.text("Parties Involved", 20, 170);
  doc.line(20, 172, 190, 172);
  
  doc.setFontSize(12);
  doc.text("Seller:", 20, 185);
  doc.text(seller.companyName, 50, 185);
  doc.text(`VAT: ${seller.vatNumber}`, 50, 192);
  
  doc.text("Buyer:", 20, 210);
  doc.text(buyer.companyName, 50, 210);
  doc.text(`VAT: ${buyer.vatNumber}`, 50, 217);
  
  // Footer
  doc.setFontSize(10);
  doc.setTextColor(150, 150, 150);
  doc.text("This certificate is automatically generated by Hartlepool Industrial Exchange (HiX).", 105, 270, { align: "center" });
  doc.text("HiX LTD | Hartlepool, UK | www.hix-exchange.com", 105, 277, { align: "center" });
  
  doc.save(`HiX-Certificate-${transaction.id}.pdf`);
}
